# GitHub Nodejs CI
name: nodejs

on: ["push"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: ["12.x", "14.x"]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: npm install, build, and test
        run: |
          npm install
          npm run test
          npm run-script test-coverage
          npm run-script test-phantom
          npm run-script test-local
        env:
          CI: true
